~?!i&32768
~o|295
batchin=?
reports=8_calculate_intrazonal_skims.rpt
~/
~/
~/begin: 8_calculate_intrazonal_skims.mac
~/ ...call module 3.21: matrix calculations
~/ ...calculate intrazonal distance, times
3.21
~+|1|y|mf"izdist"|n|sqrt(mo"tazacr"/640)*45/60*(p.eq.q)|||n|2
~+|1|y|mf"izatim"|n|mf"izdist"*(60/15)|||n|2
~+|1|y|mf"izbtim"|n|mf"izdist"*(60/10)|||n|2
~+|1|y|mf"izwtim"|n|mf"izdist"*(60/3)|||n|2
q
~#
~/end: 8_calculate_intrazonal_skims.mac
~/exit emme
~/
q
