SPEC: park_and_ride_lot_choice.csv

COEFFICIENTS: park_and_ride_lot_choice_coeffs.csv

preprocessor:
  SPEC: park_and_ride_lot_choice_preprocessor.csv
  DF: df
  TABLES:
    - land_use
    # - vehicles
    - tours

LANDUSE_PNR_SPACES_COLUMN: PNR_SPACES

# will check the tour destination to make sure transit access is available
# if no transit access, then no PNR lot will be available and could get 
# zero probabilities error
TRANSIT_SKIMS_FOR_ELIGIBILITY:
  - ivtwa__PM
  - ivtwa__MD

# Precompute destination eligibility for tours
# LANDUSE_COL_FOR_PNR_ELIGIBLE_DEST: is_pnr_eligible_destination

ITERATE_WITH_TOUR_MODE_CHOICE: False
MAX_ITERATIONS: 5
ACCEPTED_TOLERANCE: 0.95
RESAMPLE_STRATEGY: latest
PARK_AND_RIDE_MODES: # should match tour_mode_choice configs
  - DRIVE_TRN

compute_settings:
  protect_columns:
  - out_period
  - in_period