# toml input notes:
# dictionary keys are always interpreted as strings
# there’s no way to mark the end of a TOML table: all dictionaries/tables come after all other values

##############################
# Input paths and model years
##############################
protected_namespaces = '()'
debug_skims_and_paths = false
model_year = '2050'
base_year = '2023'
landuse_inputs = 'base_year_2023_2050'
network_inputs = '2050_constrained_final_revised'
db_name = 'soundcast_inputs_2023.db'
soundcast_inputs_dir = 'R:/e2projects_two/SoundCast/Inputs/dev'
abm_model = 'daysim'
##############################
# Initial Setup
##############################
run_accessibility_calcs = true
run_setup_emme_project_folders = true
run_setup_emme_bank_folders = true
run_copy_scenario_inputs = true
run_import_networks = true

##############################
# Model Procedures
##############################
run_skims_and_paths_free_flow = true
run_skims_and_paths = true
run_truck_model = true
run_supplemental_trips = true
run_daysim = true
run_summaries = true

##############################
# Modes and Path Types
##############################
include_av = false
include_tnc = true
tnc_av = false    # TNCs (if available) are AVs
include_tnc_to_transit = false # AV to transit path type allowed
include_knr_to_transit = false # Kiss and Ride to Transit
include_delivery = false
include_telecommute = true

##############################
# Other Controls
##############################
run_integrated = false
should_build_shadow_price = false
delete_banks = false
include_tnc_emissions = false

##############################
# Pricing
##############################
add_distance_pricing = true
[distance_rate_dict]
am = 2.6
md = 2.6
pm = 2.6
ev = 2.6
ni = 2.6