################################################################
# run validation notebooks
################################################################
network_summary_list = ['transit_validation',
                         'traffic_validation',
                         'bike_validation'
                        ]
# summary_list = ["get_data", # always include get_data
#                 'all_tour_mode',
#                 'all_trip_mode',
#                 'auto_ownership',
#                 'day_pattern',
#                 'escort_tour_mode',
#                 'escort_trip_mode',
#                 'households',
#                 'intermediate_stop_generation',
#                 'other_home_based_tour_mode',
#                 'other_home_based_trip_mode',
#                 'persons',
#                 'school_location',
#                 'school_tour_mode',
#                 'school_trip_mode',
#                 'telecommute_analysis',
#                 'telecommute',
#                 'time_choice',
#                 'tour_destination',
#                 'tours',
#                 'transit_pass_ownership',
#                 'trip_destination',
#                 'trips',
#                 'work_location',
#                 'work_tour_mode',
#                 'work_trip_mode',
#                 'workbased_subtour_mode',
#                 'workbased_subtour_generation',
#                 'erase_data'
#                 ]
summary_list = ['telecommute']



# color palatte for plots
psrc_color = ["#91268F", "#8CC63E", "#00A7A0", "#F05A28", "#4C4C4C", "#630460", "#9f3913", "#588527", "#00716c", "#3e4040"]


################################################################
# Validation input files and output directory names
################################################################

# other validation dataset
p_acs_auto_ownership = "R:/e2projects_two/activitysim/estimation/2017_2019_data/validation_data/auto_ownership/bg_auto_ownership.csv"
p_maz_bg_lookup =      "R:/e2projects_two/activitysim/estimation/2017_2019_data/validation_data/auto_ownership/maz_bg_lookup.csv"

# validation output directory
p_output_dir = "outputs/2023_validation"

# ---- model results
# - local soundcast run
model_dir = '../../../..'

# - (JL: for summary development)
# model_dir = "//modelstation2/c$/Workspace/sc_2023_01_02_25"

# ---- survey results
# attach uncloned folder path when reading uncloned data
uncloned_folder = "uncloned"

# list all survey sources to be indluded in validation
[survey_directories]
## updated 2023
"survey" = "R:/e2projects_two/2023_base_year/2023_survey/daysim_format/updated_weights_12_30_24/cleaned/skims_attached"

# 2017/2019
"survey (2017/2019)" = "R:/e2projects_two/2023_base_year/2017_2019_survey/test/cleaned/skims_attached"
# 2023 old weights
# "survey (old weights)" = "R:/e2projects_two/2023_base_year/2023_survey/daysim_format/cleaned/skims_attached"
